nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: 1AD3881A-119F-46DC-812D-83204A2B7176
    npmRegistryServer: https://npm.fontawesome.com

yarnPath: .yarn/releases/yarn-3.1.1.cjs
